name: release-init

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to release. Ex: v1.0.0'
        required: true
        default: 'v1.0.0'        
      likec4:
        description: 'likec4 version to bundle. Ex: 1.0.0'
        required: false
        default: 'latest'
      playwright:
        description: 'playwright version. Ex: v1.42.1'
        required: false
        default: ''        

permissions:
  contents: write
  pull-requests: write

jobs:
  release-init:
    if: "github.ref == 'refs/heads/main'"
    name: Prepare Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: wow-actions/use-app-token@0309c8980f645daa15f8909e70e6db96f3794999 # v2
        id: likec4-bot
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ env.BOT_TOKEN }}

      - name: check for tag
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
        run: |
          TAG="${INPUT_VERSION}"
          if [ "$(git tag -l "${TAG}")"  ]; then
            echo "::error::Tag ${TAG} exists"
            exit 1
          fi          

      - name: update Dockerfile
        uses: jacobtomlinson/gha-find-replace@2ff30f644d2e0078fc028beb9193f5ff0dcad39e # v3
        with:
          find: "ARG LIKEC4_VER.*"
          replace: "ARG LIKEC4_VER=${{ github.event.inputs.likec4 || 'latest' }}"          
          include: "Dockerfile"
          
      - name: update Playwright
        if: ${{ github.event.inputs.playwright != '' }}
        uses: jacobtomlinson/gha-find-replace@2ff30f644d2e0078fc028beb9193f5ff0dcad39e # v3
        with:
          find: "playwright\\:.*-jammy"
          replace: "playwright:${{ github.event.inputs.playwright }}-jammy"          
          include: "Dockerfile"        

      - name: review Dockerfile
        run: cat Dockerfile

      - name: update action.yml
        uses: jacobtomlinson/gha-find-replace@2ff30f644d2e0078fc028beb9193f5ff0dcad39e # v3
        with:
          find: ".*image\\:.*"
          replace: '  image: docker://ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}'
          include: "action.yml"     

      - name: review action.yml
        run: cat action.yml 

      - name: create pull request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          token: ${{ env.BOT_TOKEN }}
          commit-message: "release: ${{ github.event.inputs.version }}"
          title: "release: ${{ github.event.inputs.version }}"
          body: |
            likec4 version: ${{ github.event.inputs.likec4 || 'latest' }}
          branch: release/${{ github.event.inputs.version }}
          base: main
          delete-branch: true        
